; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
monitor_speed = 115200
build_flags =
    -std=gnu++11

;[env:native]
;platform = native
;build_flags =
;    -std=gnu++11
;    -DUNITY_INCLUDE_DOUBLE
;    -DNATIVE_TEST
;    -I test/test_sml_parser
;    -I include
;test_build_src = false
